src/MICmdCmdBreak.cpp

Fixes: https://bugs.llvm.org/show_bug.cgi?id=28698
According to [this](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Breakpoint-Commands.html#GDB_002fMI-Breakpoint-Commands) document, `-break-insert`'s `-f` flag is to tell the debugger to create a pending breakpoint if the location is not found. The additional parameter should not be necessary.
```
‘-f’
If location cannot be parsed (for example if it refers to unknown files or functions), create a pending breakpoint. Without this flag, GDB will report an error, and won’t create a breakpoint, if location cannot be parsed.
‘-d’
```

Update -break-insert with the -f (pending flag) to not require an additional parameter

---

src/CMakeLists.txt

Fedora 30 has libLLVMSupport only in 'llvm-static' which does not need to be
installed:
```
[100%] Linking CXX executable lldb-mi
/usr/bin/ld: cannot find -lLLVMSupport
collect2: error: ld returned 1 exit status
```
Also I had some compatibility problem linking both static and dynamic libraries:
```
: CommandLine Error: Option 'disable-symbolication' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

Simplify linked libraries: LLVMSupport -> LLVM

---

CMakeLists.txt

set(CMAKE_CXX_STANDARD 11) will pass -std=gnu++11, which breaks builds that use libc++ instead of libstdc++. Instead of that, use the llvm cmake module HandleLLVMStdlib.cmake.

Use llvm cmake module to set stdlib

---

CMakeLists.txt

llvm's minimum required cmake version is 3.4.3. This changes lldb-mi's requirement from 3.11 to 3.4.3, to match llvm.

Change minimum required cmake version to match llvm.

---

CMakeLists.txt

HandleLLVMOption is where flags like -std are set in LLVM. Instead of duplicating
that logic, include this file in lldb-mi as well.
Also set the CMP0077 policy like LLVM does so that we don't get warnings.
Closes #17
Signed-off-by: Marc-Andre Laperle <malaperle@gmail.com>

Include HandleLLVMOptions.cmake to inherit common compile flags

---

src/MICmdBase.cpp

Errors messages as coming from the LLDB may contain new line characters,
which are forbidden inside of the MI reply and must be escaped in the
output.
This fixes a problem where LLDB would return the Status with a multiline
string and Eclipse would show only the first line of the message, trimming
the rest.

Escape string in the error message

---

src/MICmdCmdData.cpp
src/MICmdCmdData.h

This commit fixes an issue with -data-info-line which would return its
result without a proper token. Output should look like this:
```
7-data-info-line *0x4
7^done,start="0x4",end="0xc",file="file.c",line="65"
```
But it was looking look this:
```
7-data-info-line *0x4
^done,start="0x4",end="0xc",file="file.c",line="65"
```
As a a result of missing token, requester couldn't match the result with the
request. Apparently the fix is that token in the result record should not be
set in the constructor of the CMICmdCmdDataInfoLine class.

Fix data-info-line command result

---

CMakeLists.txt
src/CMakeLists.txt

This commit fixes runtime error
```
: CommandLine Error: Option 'disable-symbolication' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
Linking only the LLVMSupport from the same location also led to this error (i.e. an another LLVM shared library was loaded at runtime?)
Should also fix #8

Link libraries from the LLVM_LIBRARY_DIRS location

---

src/MIUtilString.cpp

Current string utilities implementation ignores absence of `0x` during
hexadecimal numbers extraction and it can lead to some non-obvious
bugs. For example, because of this, the debugger understands a
breakpoint on function `f` as a breakpoint on address 0xf.

Fix hexadecimal numbers parsing

---

src/MICmdCmdSupportList.cpp

Adding `pending-breakpoints` to the list to indicate that there
is support for the -f option to the `-break-insert` command.
[Documentation ](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Support-Commands.html#GDB_002fMI-Support-Commands) from GDB-MI 
Support is seen in
https://github.com/lldb-tools/lldb-mi/blob/1fa7523e9f4988d63e77974fb660bbd9976bd036/src/MICmdCmdBreak.cpp#L46
and parsing is in
https://github.com/lldb-tools/lldb-mi/blob/1fa7523e9f4988d63e77974fb660bbd9976bd036/src/MICmdCmdBreak.cpp#L83

Add 'pending-breakpoints' to 'list-features' list

---

CMakeLists.txt
src/CMakeLists.txt

This allows lldb-mi to be built and installed to an arbitrary directory.

Add install target and set the rpath

---

src/MICmdCmdBreak.cpp

Fix for following build error:
CMake Error at src/CMakeLists.txt:100 (install):
install TARGETS given no RUNTIME DESTINATION for executable target
"lldb-mi".

Add RUNTIME DESTINATION to install target

---

CMakeLists.txt
README.md
src/CMakeLists.txt

This PR changes the CMakeLists.txt to support building lldb-mi with
LLDB.framework when building LLVM/LLDB with `-DLLDB_BUILD_FRAMEWORK=1`.
When building LLDB-MI, you will need to pass in `USE_LLDB_FRAMEWORK `.
Addresses https://github.com/lldb-tools/lldb-mi/issues/36

Build lldb-mi with LLDB.framework

---

CMakeLists.txt

Current CMakeLists.txt forces a specific content into the final RPATH,
in particular that it should contain an absolute path to the
installation directory. This is not always optimal, as relocatable
applications on Linux require there to be a path relative to $ORIGIN.
It is possible to ensure that $ORIGIN will be in the RPATH by using a
-Wl,rpath= with a desired value, but this is basically a hack that
bypasses cmake mechanisms. Better approach would be to modify
CMakeLists.txt to respect values that are passed from the command line
via -D option.
Default behavior is not changed by this change.

Fix handling of RPATH variables on cmake invocation

---

src/MIDataTypes.h

Fixes the error reported in #52

Define NOMINMAX to suppress the min and max macros in Windef.h

---

.travis.yml

Recently builds started to fail due to the missed dependency on gmock library. Trying to fix builds.

[CI] Install gmock

---

src/MICmnLLDBDebugSessionInfoVarObj.cpp

This became unused in 669a3456a877683c81e3d80016b75b3827a138eb.

Remove an unused variable

---

src/MICmnLLDBDebugSessionInfo.cpp
src/MICmnLLDBDebugSessionInfo.h

This fixes this warning:
../src/MICmnLLDBDebugSessionInfo.cpp:55:7: warning: field 'm_bCreateTty' will be initialized after field 'm_nNextMiStoppointId' [-Wreorder-ctor]
m_bCreateTty(false), m_nNextMiStoppointId(1UL) {}
^

Avoid warnings by initializing fields in the right order

---

src/MICmnLLDBDebugSessionInfo.cpp

This fixes warnings like these:
../src/MICmnLLDBDebugSessionInfo.cpp:877:17: warning: unused function 'GetBreakOrWatchPointAddress<lldb::SBBreakpoint>' [-Wunused-function]
lldb::SBAddress GetBreakOrWatchPointAddress(lldb::SBTarget &vrTarget,
^
../src/MICmnLLDBDebugSessionInfo.cpp:884:17: warning: unused function 'GetBreakOrWatchPointAddress<lldb::SBWatchpoint>' [-Wunused-function]
lldb::SBAddress GetBreakOrWatchPointAddress(lldb::SBTarget &vrTarget,
^
Alternative they could be removed altogether.

Avoid warnings by removing 'static' from templates that currently are unused

---

src/MICmnStreamStdin.cpp
src/MIDataTypes.h
src/MIUtilDebug.cpp
src/Platform.h

Platform.h includes lldb/Host/windows/windows.h, which overrides e.g.
NTDDI_VERSION and _WIN32_WINNT before including <windows.h>. If
we directly include <windows.h> somewhere first, and then later
include lldb/Host/windows/windows.h (via Platform.h) we end up
redefining NTDDI_VERSION.
Also include lldb/Host/windows/PosixApi.h (for consistency, as it
ends up included in some files but not in others) and add ifdefs
around some defines that are defined by lldb's PosixApi.h. (Adding
ifdefs instead of removing the definitions altogether, as older
versions of lldb might not have the same defines.)

Consistently include "Platform.h" instead of including <windows.h>

---

src/CMakeLists.txt

This is now required in order to be able to build with the very
latest llvm-project from git main.

Increase CXX_STANDARD to 17

---

.github/workflows/ci.yml
.gitignore
README.md

I noticed that the CI has been failing for a long time because the Windows version of CI depends on the artifact of `tkrasnukha/install-llvm`. However, this repo is no longer usable because the artifact has not been updated for a long time. So I switched repos to fix this issue. At the same time, I also made some other changes.

fix windows build error in CI

---

src/MICmnLLDBDebugSessionInfo.cpp

This PR adds a small fix to improve handling of absolute Unix-style paths in Win32 versions of lldb-mi.
Some details about the issue and the suggested fix:
When using lldb-mi to remotely debug a binary on a Linux system, I noticed frequent long stalls (> 10 seconds) when pausing execution or hitting a breakpoint. Further investigation revealed CMICmnLLDBDebugSessionInfo::ResolvePath() as the affected function; the delays were caused by waiting for a call to access() to complete. The path being tested started with two backslashes, and was thus interpreted as an UNC path to a nonexistent network server.
The suggested fix is to switch forward slashes to backslashes in the path to resolve, so the rest of the function will be able to split the path correctly. The reason for the double …

Win32: Change incoming path slashes to backslashes in ResolvePath

---

src/MICmnLLDBDebuggerHandleEvents.cpp

Add missing switch cases to MICmnLLDBDebuggerHandleEvents.cpp to fix the following warning:
```
/Users/pivovaa/workspace/lldb-mi/src/MICmnLLDBDebuggerHandleEvents.cpp:1133:11: warning: 4 enumeration values not handled in switch: 'eStopReasonProcessorTrace', 'eStopReasonFork', 'eStopReasonVFork'... [-Wswitch]
switch (eStoppedReason) {
^~~~~~~~~~~~~~
/Users/pivovaa/workspace/lldb-mi/src/MICmnLLDBDebuggerHandleEvents.cpp:1133:11: note: add missing switch cases
switch (eStoppedReason) {
^
1 warning generated.
```

Add missing cases to MICmnLLDBDebuggerHandleEvents.cpp

---

src/MICmdCmdBreak.cpp
src/MICmdCmdSymbol.cpp
src/MICmnLLDBDebugSessionInfo.cpp
src/MICmnLLDBDebugSessionInfo.h

before this patch:
after this patch:
```
(gdb)
-target-attach 43992
^done
=thread-group-started,id="i1",pid="43992"
(gdb)
=thread-created,id="1",group-id="i1"
=thread-created,id="2",group-id="i1"
=thread-created,id="3",group-id="i1"
=thread-selected,id="1"
(gdb)
=library-loaded,id="/usr/lib/dyld",target-name="/usr/lib/dyld",host-name="/usr/lib/dyld",symbols-loaded="0",loaded_addr="0x000000011156a000",size="602112"
=library-loaded,id="/System/Applications/TextEdit.app/Contents/MacOS/TextEdit",target-name="/System/Applications/TextEdit.app/Contents/MacOS/TextEdit",host-name="/System/Applications/TextEdit.app/Contents/MacOS/TextEdit",symbols-loaded="0",loaded_addr="0x0000000101f28000",size="110592"
=library-loaded,id="/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa",target-name="/ …
```

Fix the problem that the module list cannot be obtained

---

src/MICmdCmdVar.cpp

This change comes from the [clayborg ](https://github.com/clayborg)'s comment in https://github.com/lldb-tools/lldb-mi/pull/115#discussion_r1706360623 and should help solve  the memory leak issues mentioned in https://github.com/lldb-tools/lldb-mi/pull/115.
---------
Co-authored-by: Greg Clayton <clayborg@gmail.com>

Remove the traversal of the SBValue's children values

---

CMakeLists.txt
src/MICmdBase.cpp
test/unittests/CMakeLists.txt

CMake 4.0 removed compatibility with CMake versions below 3.5. Therefore, it errors out on projects with a
cmake_minimum_required() less than 3.5.
(Since the last versions of CMake before 4.0, it already has been warning that compatibility with versions below 3.10 is deprecated.)
Thus - this fixes building with CMake 4.0.

Bump the minimum CMake version to match current LLVM

---

.github/workflows/ci.yml

Hi! This PR is made by Step Security bot who's used to help us follow the best security practice. [GitHub](https://docs.github.com/en/actions/reference/secure-use-reference#use-secrets-for-sensitive-information) recommends setting minimum token permissions for the GITHUB_TOKEN.
(PS: I'm working for the potential risks of software supply attacks. So I'm trying to write some PRs to help opensource community fix security issues.)

ci: restrict the permissions of the ci workflow
